"""GENERATED FILE — do not edit. Source: packages/schemas/src/*.json (run scripts/generate.py).

sitara_schemas — the shared frozen contracts (SPEC §34.3/§34.4/§34.6).
"""

from sitara_schemas.errors import (
    DEFAULT_RETRYABLE,
    HTTP_STATUS,
    ErrorCode,
    ErrorEnvelope,
)
from sitara_schemas.chat import (
    SAFETY_LEVEL_ORDINAL,
    SAFETY_TAKEOVER_FROM_ORDINAL,
    ChatCitation,
    ChatRole,
    ChatTrust,
    ChatTurn,
    MemoryChipOffer,
    SafetyLevel,
    SourceState,
)
from sitara_schemas.memory_types import MEMORY_TYPE_ORDER, MemoryType
from sitara_schemas.modules import MORNING_MODULE_ORDER, MorningModule
from sitara_schemas.presence import (
    PRESENCE_CINEMAGRAPH,
    PRESENCE_ORDINAL,
    PresenceState,
)
from sitara_schemas.voice import (
    BARGE_IN_REASONS,
    ENTITLEMENT_WARNING_MINUTES,
    HOLDING_PHRASE_AFTER_MS,
    MAX_NOTE_DURATION_MS,
    PLAYBACK_POLICIES,
    SOURCE_AUDIO_RETENTION_DAYS,
    TRANSCRIPT_STATUSES,
    VAD_STATES,
    BargeInReason,
    PlaybackPolicy,
    TranscriptStatus,
    VadState,
)
from sitara_schemas.ws_events import (
    BINARY_AUDIO_FORMAT,
    BINARY_CHANNELS,
    BINARY_HEADER_BYTES,
    BINARY_HEADER_FLAGS_BYTES,
    BINARY_HEADER_SEQ_BYTES,
    BINARY_SAMPLE_RATE_HZ,
    HEARTBEAT_INTERVAL_S,
    REAP_AFTER_SILENCE_S,
    RESUME_WINDOW_S,
    BargeInPayload,
    ControlEvent,
    ControlEventType,
    EntitlementWarningPayload,
    HandoffToTextPayload,
    PartialCaptionPayload,
    PresenceStatePayload,
    ResumeOfferPayload,
    SessionReadyPayload,
    SessionStartPayload,
    TaraTurnPayload,
    TtsChunkMetaPayload,
    TtsEndPayload,
    TtsStartPayload,
    UserTurnPayload,
    VadStatePayload,
)

__all__ = [
    "BARGE_IN_REASONS",
    "BINARY_AUDIO_FORMAT",
    "BINARY_CHANNELS",
    "BINARY_HEADER_BYTES",
    "BINARY_HEADER_FLAGS_BYTES",
    "BINARY_HEADER_SEQ_BYTES",
    "BINARY_SAMPLE_RATE_HZ",
    "BargeInPayload",
    "BargeInReason",
    "ChatCitation",
    "ChatRole",
    "ChatTrust",
    "ChatTurn",
    "ControlEvent",
    "ControlEventType",
    "DEFAULT_RETRYABLE",
    "ENTITLEMENT_WARNING_MINUTES",
    "EntitlementWarningPayload",
    "ErrorCode",
    "ErrorEnvelope",
    "HEARTBEAT_INTERVAL_S",
    "HOLDING_PHRASE_AFTER_MS",
    "HTTP_STATUS",
    "HandoffToTextPayload",
    "MAX_NOTE_DURATION_MS",
    "MEMORY_TYPE_ORDER",
    "MORNING_MODULE_ORDER",
    "MemoryChipOffer",
    "MemoryType",
    "MorningModule",
    "PLAYBACK_POLICIES",
    "PRESENCE_CINEMAGRAPH",
    "PRESENCE_ORDINAL",
    "PartialCaptionPayload",
    "PlaybackPolicy",
    "PresenceState",
    "PresenceStatePayload",
    "REAP_AFTER_SILENCE_S",
    "RESUME_WINDOW_S",
    "ResumeOfferPayload",
    "SAFETY_LEVEL_ORDINAL",
    "SAFETY_TAKEOVER_FROM_ORDINAL",
    "SOURCE_AUDIO_RETENTION_DAYS",
    "SafetyLevel",
    "SessionReadyPayload",
    "SessionStartPayload",
    "SourceState",
    "TRANSCRIPT_STATUSES",
    "TaraTurnPayload",
    "TranscriptStatus",
    "TtsChunkMetaPayload",
    "TtsEndPayload",
    "TtsStartPayload",
    "UserTurnPayload",
    "VAD_STATES",
    "VadState",
    "VadStatePayload",
]
