"""GENERATED FILE — do not edit. Source: packages/schemas/src/*.json (run scripts/generate.py)."""

from enum import StrEnum

from pydantic import BaseModel, ConfigDict


class ErrorCode(StrEnum):
    """SPEC §6.3 / §34.4 — namespaced error codes (closed namespaces:
    AUTH_/ASTRO_/VOICE_/PAY_/SAFE_/SYS_). New codes are PR-reviewed.
    """

    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED"
    AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
    AUTH_UNDERAGE = "AUTH_UNDERAGE"
    AUTH_OTP_THROTTLED = "AUTH_OTP_THROTTLED"
    AUTH_PROVIDER_CONFLICT = "AUTH_PROVIDER_CONFLICT"
    ASTRO_INSUFFICIENT_BIRTH_DATA = "ASTRO_INSUFFICIENT_BIRTH_DATA"
    ASTRO_PLACE_UNRESOLVED = "ASTRO_PLACE_UNRESOLVED"
    ASTRO_ENGINE_UNAVAILABLE = "ASTRO_ENGINE_UNAVAILABLE"
    ASTRO_PROVIDER_DISPUTED = "ASTRO_PROVIDER_DISPUTED"
    ASTRO_NAME_UNCONFIRMED = "ASTRO_NAME_UNCONFIRMED"
    ASTRO_NAME_INVALID = "ASTRO_NAME_INVALID"
    VOICE_PROVIDER_UNAVAILABLE = "VOICE_PROVIDER_UNAVAILABLE"
    VOICE_MINUTES_EXHAUSTED = "VOICE_MINUTES_EXHAUSTED"
    VOICE_SESSION_NOT_FOUND = "VOICE_SESSION_NOT_FOUND"
    PAY_PAYMENT_REQUIRED = "PAY_PAYMENT_REQUIRED"
    PAY_WEBHOOK_DUPLICATE = "PAY_WEBHOOK_DUPLICATE"
    PAY_PROVIDER_ERROR = "PAY_PROVIDER_ERROR"
    SAFE_CONTENT_BLOCKED = "SAFE_CONTENT_BLOCKED"
    SAFE_REVIEW_PENDING = "SAFE_REVIEW_PENDING"
    SYS_VALIDATION = "SYS_VALIDATION"
    SYS_RATE_LIMITED = "SYS_RATE_LIMITED"
    SYS_IDEMPOTENCY_CONFLICT = "SYS_IDEMPOTENCY_CONFLICT"
    SYS_INTERNAL = "SYS_INTERNAL"
    SYS_UNAVAILABLE = "SYS_UNAVAILABLE"


HTTP_STATUS: dict[ErrorCode, int] = {
    ErrorCode.AUTH_INVALID_TOKEN: 401,
    ErrorCode.AUTH_SESSION_EXPIRED: 401,
    ErrorCode.AUTH_FORBIDDEN: 403,
    ErrorCode.AUTH_UNDERAGE: 422,
    ErrorCode.AUTH_OTP_THROTTLED: 429,
    ErrorCode.AUTH_PROVIDER_CONFLICT: 409,
    ErrorCode.ASTRO_INSUFFICIENT_BIRTH_DATA: 422,
    ErrorCode.ASTRO_PLACE_UNRESOLVED: 422,
    ErrorCode.ASTRO_ENGINE_UNAVAILABLE: 503,
    ErrorCode.ASTRO_PROVIDER_DISPUTED: 409,
    ErrorCode.ASTRO_NAME_UNCONFIRMED: 422,
    ErrorCode.ASTRO_NAME_INVALID: 400,
    ErrorCode.VOICE_PROVIDER_UNAVAILABLE: 503,
    ErrorCode.VOICE_MINUTES_EXHAUSTED: 402,
    ErrorCode.VOICE_SESSION_NOT_FOUND: 404,
    ErrorCode.PAY_PAYMENT_REQUIRED: 402,
    ErrorCode.PAY_WEBHOOK_DUPLICATE: 409,
    ErrorCode.PAY_PROVIDER_ERROR: 502,
    ErrorCode.SAFE_CONTENT_BLOCKED: 422,
    ErrorCode.SAFE_REVIEW_PENDING: 422,
    ErrorCode.SYS_VALIDATION: 400,
    ErrorCode.SYS_RATE_LIMITED: 429,
    ErrorCode.SYS_IDEMPOTENCY_CONFLICT: 409,
    ErrorCode.SYS_INTERNAL: 500,
    ErrorCode.SYS_UNAVAILABLE: 503,
}

DEFAULT_RETRYABLE: dict[ErrorCode, bool] = {
    ErrorCode.AUTH_INVALID_TOKEN: False,
    ErrorCode.AUTH_SESSION_EXPIRED: False,
    ErrorCode.AUTH_FORBIDDEN: False,
    ErrorCode.AUTH_UNDERAGE: False,
    ErrorCode.AUTH_OTP_THROTTLED: True,
    ErrorCode.AUTH_PROVIDER_CONFLICT: False,
    ErrorCode.ASTRO_INSUFFICIENT_BIRTH_DATA: False,
    ErrorCode.ASTRO_PLACE_UNRESOLVED: False,
    ErrorCode.ASTRO_ENGINE_UNAVAILABLE: True,
    ErrorCode.ASTRO_PROVIDER_DISPUTED: False,
    ErrorCode.ASTRO_NAME_UNCONFIRMED: False,
    ErrorCode.ASTRO_NAME_INVALID: False,
    ErrorCode.VOICE_PROVIDER_UNAVAILABLE: True,
    ErrorCode.VOICE_MINUTES_EXHAUSTED: False,
    ErrorCode.VOICE_SESSION_NOT_FOUND: False,
    ErrorCode.PAY_PAYMENT_REQUIRED: False,
    ErrorCode.PAY_WEBHOOK_DUPLICATE: False,
    ErrorCode.PAY_PROVIDER_ERROR: True,
    ErrorCode.SAFE_CONTENT_BLOCKED: False,
    ErrorCode.SAFE_REVIEW_PENDING: False,
    ErrorCode.SYS_VALIDATION: False,
    ErrorCode.SYS_RATE_LIMITED: True,
    ErrorCode.SYS_IDEMPOTENCY_CONFLICT: False,
    ErrorCode.SYS_INTERNAL: True,
    ErrorCode.SYS_UNAVAILABLE: True,
}


class ErrorEnvelope(BaseModel):
    """SPEC §34.4 — the ONE canonical error envelope. No module invents its own."""

    model_config = ConfigDict(frozen=True)

    code: ErrorCode
    message_key: str
    trace_id: str
    retryable: bool
